//! Serializes `cargo xtask bench logs-read`'s evidence to JSON
//! (`docs/benchmarks/data/*.json`, matching `ch-bench --out`'s convention)
//! and renders a markdown table body suitable for pasting into
//! `docs/benchmarks/m1-logs-read-path.md`.

use super::Profile;
use super::dataset::DatasetSummary;
use super::queries::QueryEvidence;

#[derive(Debug, Clone, serde::Serialize)]
pub struct BenchReport {
    pub profile: Profile,
    pub seed: u64,
    pub dist: bool,
    pub cluster: Option<String>,
    pub dataset: DatasetSummary,
    pub queries: Vec<QueryEvidence>,
}

/// Renders the query-evidence table body (issue #16: "CI-scale numbers …
/// labelled 'CI-scale, not comparable to the §9 target'" per the report's
/// two-tier banner). Every row is rendered — this tool does not know which
/// rows are §9-mapped vs. the nearest-analog rollup shape; that curation
/// happens in the committed report, not here.
pub fn render_markdown(report: &BenchReport) -> String {
    let mut out = String::new();
    out.push_str(&format!(
        "<!-- generated by `cargo xtask bench logs-read` (profile={:?}, seed={}, dist={}) -->\n",
        report.profile, report.seed, report.dist
    ));
    out.push_str(&format!(
        "Dataset: {} rows, {} streams, {} services, {} needle rows, loaded in {} ms.\n\n",
        report.dataset.total_rows,
        report.dataset.streams,
        report.dataset.services,
        report.dataset.needle_rows,
        report.dataset.load_elapsed_ms,
    ));
    out.push_str(
        "| Query | wall p50 (ms) | wall p95 (ms) | wall p99 (ms) | returned rows | read_rows | \
         selected_marks/total_marks | read_bytes | memory_usage |\n",
    );
    out.push_str("|---|---|---|---|---|---|---|---|---|\n");
    for q in &report.queries {
        out.push_str(&format!(
            "| {} | {:.1} | {:.1} | {:.1} | {} | {} | {}/{} | {} | {} |\n",
            q.name,
            q.wall_ms_p50,
            q.wall_ms_p95,
            q.wall_ms_p99,
            q.returned_rows,
            q.read_rows,
            q.selected_marks,
            q.total_marks,
            q.read_bytes,
            q.memory_usage,
        ));
    }
    if report.dist {
        out.push_str(
            "\nPer-stage, per-shard evidence (`--dist`) — issue #16 CODE review: every stage a \
             shape's read actually executes (`resolution`/`hydration`/`samples`/`rollup_range`/\
             `discovery`) is captured separately, not just the terminal stage, and **every shard \
             in the cluster is accounted for every stage** — either participating or provably, \
             derivedly pruned. **Schema note (expected-roster model).** `role` is \
             `coordinator-local` (the initiator's own `is_initial_query = 1` row — its \
             in-process local-shard read under `prefer_localhost_replica = 1`), `remote` \
             (`is_initial_query = 0`, a participating non-initiator shard), or `expected-pruned` \
             (a shard `optimize_skip_unused_shards` correctly excluded — `read_rows`/\
             `read_bytes`/`selected_marks` are `0`, and `pruned_reason` spells out the \
             `fingerprint % total_weight` derivation). **Unpruned stages** (`resolution`, \
             `discovery` — no `fingerprint` predicate to prune by) show every shard \
             **participating**. **Fingerprint-scoped stages** (`hydration`, `samples`, \
             `rollup_range`) show exactly the *computed owning subset* participating, with every \
             other shard `expected-pruned` — full roster **accounted for**, not full roster \
             **participating**. **Totals-overlap caveat:** the `coordinator-local` row is the \
             *same* row this table's per-query `read_rows`/etc. columns above come from — those \
             are the initiator's own local reads, not a cluster-wide sum; a cluster-wide total is \
             `coordinator-local.read_rows + Σ remote.read_rows` (excluding `expected-pruned` \
             rows, which contribute `0`).\n\n",
        );
        out.push_str(
            "| Query | stage | shard_num | role | hostname | read_rows | read_bytes | \
             selected_marks | pruned_reason |\n",
        );
        out.push_str("|---|---|---|---|---|---|---|---|---|\n");
        for q in &report.queries {
            for stage in &q.stage_evidence {
                for shard in &stage.shards {
                    out.push_str(&format!(
                        "| {} | {} | {} | {} | {} | {} | {} | {} | {} |\n",
                        q.name,
                        stage.stage,
                        shard.shard_num,
                        shard.role,
                        shard.hostname,
                        shard.read_rows,
                        shard.read_bytes,
                        shard.selected_marks,
                        shard.pruned_reason.as_deref().unwrap_or("-"),
                    ));
                }
            }
        }
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    fn sample_report() -> BenchReport {
        BenchReport {
            profile: Profile::Ci,
            seed: 1,
            dist: false,
            cluster: None,
            dataset: DatasetSummary {
                total_rows: 10,
                services: 1,
                streams: 1,
                needle_rows: 1,
                start_ns: 0,
                end_ns: 1,
                load_elapsed_ms: 5,
                canonical_service: "svc-000".to_string(),
                canonical_env: "prod".to_string(),
                canonical_fingerprint: 1,
            },
            queries: vec![QueryEvidence {
                name: "example".to_string(),
                sql: "SELECT 1".to_string(),
                wall_ms_p50: 1.0,
                wall_ms_p95: 2.0,
                wall_ms_p99: 3.0,
                returned_rows: 1,
                read_rows: 1,
                read_bytes: 1,
                selected_marks: 1,
                total_marks: 1,
                memory_usage: 1,
                query_duration_ms: 1,
                explain_indexes: vec![],
                stage_evidence: vec![],
            }],
        }
    }

    #[test]
    fn render_markdown_includes_every_query_row() {
        let md = render_markdown(&sample_report());
        assert!(md.contains("example"));
        assert!(md.contains("| 1.0 | 2.0 | 3.0 |"));
    }

    #[test]
    fn bench_report_serializes_to_json() {
        let json = serde_json::to_string(&sample_report()).expect("serializes");
        assert!(json.contains("\"example\""));
    }
}
