//! Deterministic metric corpus generator for the M2 differential scenario
//! (issue #33 architect plan + amendment): three families (gauges with
//! staleness gaps, monotonic counters with resets, OTLP explicit-bucket
//! histograms) pushed **once** as OTLP metrics into the collector, which
//! fans them out — via two identical `prometheusremotewrite` exporters —
//! to both PulsusDB and a reference Prometheus (`e2e/src/metrics.rs`).
//! Because both backends ingest the collector's **own** OTLP→PRW
//! conversion (not `pulsus-write`'s Rust OTLP-metrics parser, issue #27),
//! this module only needs to emit spec-valid OTLP — it never needs to
//! reproduce the collector's or either backend's histogram-flattening
//! arithmetic.
//!
//! **PRNG:** hand-rolled `splitmix64` (issue #16 task-manager resolution
//! #3 precedent, `xtask/src/bench/dataset.rs`) — never `rand`, so a given
//! `(seed, scale)` corpus is byte-reproducible across `rand` version
//! bumps. Duplicated here rather than shared: `e2e/` has no dependency on
//! `xtask`, and `dataset.rs`'s own doc comment already establishes
//! "duplicate, don't share" as this codebase's convention for this exact
//! generator shape.
//!
//! **Determinism contract:** every value is a pure function of `(seed,
//! service_idx, instance_idx, slot_idx, ts_idx)` — no accumulated RNG
//! state threaded between calls (`counter_value` re-sums from the last
//! reset on every call rather than mutating a running total), so the
//! whole corpus can be regenerated byte-for-byte from a `CorpusSpec` alone
//! (unit tests below assert this).
//!
//! **Distinct-topk invariant (architect plan risk 4):** every family's
//! per-service base value is offset by a stride far larger than the
//! maximum possible per-instance noise summed across every instance in a
//! service, so `sum by(service)(...)` aggregates — and therefore
//! `topk`/`bottomk`/comparison-operator results — can never tie or cross
//! between services, at any timestamp, regardless of how staleness gaps
//! or counter resets fall. Verified by
//! [`tests::per_service_gauge_and_counter_totals_are_strictly_ordered`].

use std::collections::{BTreeMap, BTreeSet};

use serde::{Deserialize, Serialize};

/// Which family every identifying label is emitted under (issue #33
/// architect plan: "All identifying labels are emitted as OTLP datapoint
/// attributes, not resource attributes" — `add_metric_suffixes: false` is
/// pinned on both collector exporters, so these names travel verbatim to
/// both backends).
pub const GAUGE_METRIC: &str = "mem_usage_bytes";
pub const COUNTER_METRIC: &str = "requests_total";
pub const HISTOGRAM_METRIC: &str = "request_duration_seconds";

/// The histogram family's collector-flattened suffix names (module doc
/// comment: the actual `_bucket`/`_sum`/`_count` split happens in the
/// collector's OTLP→PRW conversion, not in this crate — these are what
/// that conversion is documented to produce). Functions, not consts
/// (`format!` isn't `const`-evaluable) — used both by [`generate`]'s
/// [`SeriesSpec`] bookkeeping and by `metrics.rs`'s completeness
/// pre-check ([`Corpus::per_metric_manifest`]), which must query
/// PulsusDB's `/api/v1/query` per **concrete** metric name: a bare
/// label-only selector with no `__name__` is `422 Unprocessable Entity`
/// ("not yet supported: selector without a concrete metric name" —
/// docs/schemas.md's metric-scoped model requires one), unlike real
/// Prometheus.
pub fn histogram_bucket_metric_name() -> String {
    format!("{HISTOGRAM_METRIC}_bucket")
}
pub fn histogram_sum_metric_name() -> String {
    format!("{HISTOGRAM_METRIC}_sum")
}
pub fn histogram_count_metric_name() -> String {
    format!("{HISTOGRAM_METRIC}_count")
}

/// The label every series in this scenario's corpus (and its StaleNaN
/// micro-case, `metrics.rs`) carries, scoping every selector in the query
/// matrix to exactly this run's data (mirrors `scenarios::RUN_ID_LABEL`,
/// issue #15 precedent) — an independent constant rather than importing
/// from `scenarios.rs`, since that constant is scoped to the logs
/// scenario's own module-private conventions.
pub const RUN_ID_LABEL: &str = "run_id";

/// Which tier a [`CorpusSpec`] sizes its families to (issue #33 amendment:
/// "the `ci` tier (~1k series) gates per-PR ... the full 10k tier ...
/// [is] required evidence for #33 closure"). Carried on [`Corpus`] purely
/// for diagnostics — every numeric knob a given run uses comes from
/// [`FamilyCounts`], not re-derived from this tag.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Scale {
    Ci,
    Full,
}

/// Per-family series-shape counts for one [`Scale`] tier (issue #33
/// architect plan: "declarative corpus params ... per-family series
/// counts per tier ... so scale/queries are adjustable without
/// recompiling" — loaded from `test/fixtures/metrics/differential.json`
/// by `metrics.rs`, not hardcoded here). `services` is shared by every
/// family (the dimension `topk`/`bottomk`/`by(service)` aggregate over).
#[derive(Debug, Clone, Copy, Deserialize, Serialize)]
pub struct FamilyCounts {
    pub services: usize,
    pub gauge_instances: usize,
    pub gauge_slots: usize,
    pub counter_instances: usize,
    pub histogram_instances: usize,
}

/// Generation parameters for one corpus (issue #33 architect plan
/// interface, extended per the amendment: `families`/`histogram_bounds`
/// replace a bare `Scale`-only sizing so the fixture file can drive series
/// counts at runtime, per this module's own doc comment).
#[derive(Debug, Clone)]
pub struct CorpusSpec {
    pub seed: u64,
    pub scale: Scale,
    pub step_ms: i64,
    pub sample_count: usize,
    pub base_ms: i64,
    pub run_id: String,
    pub families: FamilyCounts,
    pub histogram_bounds: Vec<f64>,
}

/// One gauge series' identity: `mem_usage_bytes{service,instance,slot}`.
/// `stale_from`, when set, is the sample index at which this series
/// **stops emitting** (issue #33 architect plan: "a deterministic subset
/// stops emitting partway through the window (staleness gaps)") — OTLP
/// carries no StaleNaN marker, so this is the only representation the
/// collector-fed corpus can carry (the direct-remote-write StaleNaN
/// micro-case in `metrics.rs` supplements this, per the task-manager
/// resolution).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct GaugeSeries {
    pub service_idx: usize,
    pub instance_idx: usize,
    pub slot_idx: usize,
    pub stale_from: Option<usize>,
}

/// One counter series' identity: `requests_total{service,instance}`.
/// `reset_at`, when set, is the sample index at which the cumulative value
/// **drops to zero** (architect plan: "a deterministic subset injects
/// counter resets (value drops to 0 at pinned timestamps)") before
/// resuming accumulation.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct CounterSeries {
    pub service_idx: usize,
    pub instance_idx: usize,
    pub reset_at: Option<usize>,
}

/// One histogram data-point identity: `request_duration_seconds{service,
/// instance}` — flattens (collector-side, not here — see module doc
/// comment) to `_bucket{le}` × `histogram_bounds.len() + 1` (incl. `+Inf`)
/// plus `_sum`/`_count`, "≈10 series per instance" per the architect plan.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct HistogramSeries {
    pub service_idx: usize,
    pub instance_idx: usize,
}

/// One flattened (post-collector-conversion) series' bookkeeping entry —
/// only what the completeness manifest ([`Corpus::expected_series`]/
/// [`Corpus::expected_samples`]) needs: a name (diagnostic only) and how
/// many of this corpus's timestamps it actually carries a real sample at
/// (`sample_count` for counters/histograms, which never gap; `stale_from`
/// for gauges, which may).
#[derive(Debug, Clone)]
pub struct SeriesSpec {
    pub metric_name: String,
    pub samples_emitted: usize,
}

/// One concrete, post-flatten series' full label identity plus the set of
/// activity-bucket floors (`ACTIVITY_BUCKET_MS`) it has **at least one
/// real sample in** — the basis for the historical-discovery
/// differential's expectation (issue #33 architect adjudication, finding
/// 2, `metrics.rs`'s `assert_discovery_contract_window`). This is
/// **our own documented bucket-floor contract's** answer (docs/schemas.md
/// §2.1: a query window is bucket-floored on both bounds, and any series
/// with a `metric_series` row — one per activity bucket it was ever
/// active in — whose bucket falls inside `[floor(start), floor(end)]` is
/// returned, a bounded superset of the exact-sample-window set) — **not**
/// Prometheus's exact-sample-window answer, which the differential now
/// treats as a logged reference, never the expectation, for this
/// specific class of endpoint (`/series`/`/labels`/label-values only —
/// the query **value matrix** stays a strict, never-allowlisted
/// Prometheus-equality comparison, untouched by this).
#[derive(Debug, Clone)]
pub struct DiscoverableSeries {
    pub labels: Vec<(String, String)>,
    pub buckets: BTreeSet<i64>,
}

/// A generated corpus: every family's series identities (enough to
/// rebuild every sample value via the pure `*_value`/`*_bucket_counts` fns
/// below), the flattened manifest ([`expected_series`]/[`expected_samples`]
/// — issue #33 amendment's completeness pre-check), and the window it
/// spans.
#[derive(Debug, Clone)]
pub struct Corpus {
    pub run_id: String,
    pub scale: Scale,
    pub seed: u64,
    pub base_ms: i64,
    pub step_ms: i64,
    pub sample_count: usize,
    pub gauges: Vec<GaugeSeries>,
    pub counters: Vec<CounterSeries>,
    pub histograms: Vec<HistogramSeries>,
    pub histogram_bounds: Vec<f64>,
    pub series: Vec<SeriesSpec>,
    pub expected_series: usize,
    pub expected_samples: usize,
    pub first_ts_ms: i64,
    pub last_ts_ms: i64,
}

impl Corpus {
    /// The completeness pre-check's manifest (issue #33 code review,
    /// [medium]): metric name -> exact `(expected_series,
    /// expected_samples)`, derived from [`Self::series`] — **per metric
    /// name**, never collapsed to a grand total (a compensating miscount
    /// across metric families, e.g. `mem_usage_bytes` short 5,
    /// `requests_total` over by 5, would otherwise net to the same total
    /// and false-pass a sum-only comparison — see `metrics.rs`'s
    /// `Manifest` type).
    pub fn per_metric_manifest(&self) -> BTreeMap<String, (usize, usize)> {
        let mut manifest: BTreeMap<String, (usize, usize)> = BTreeMap::new();
        for s in &self.series {
            let entry = manifest.entry(s.metric_name.clone()).or_insert((0, 0));
            entry.0 += 1;
            entry.1 += s.samples_emitted;
        }
        manifest
    }

    /// Every concrete, post-flatten series this corpus produces, with its
    /// exact label identity and activity-bucket footprint — see
    /// [`DiscoverableSeries`]'s doc comment for what this is used for and
    /// why it is *our* documented contract's answer, not Prometheus's.
    pub fn discoverable_series(&self) -> Vec<DiscoverableSeries> {
        let mut out = Vec::with_capacity(self.expected_series);

        for g in &self.gauges {
            let last_idx = g.stale_from.unwrap_or(self.sample_count).saturating_sub(1);
            out.push(DiscoverableSeries {
                labels: sorted_labels(&[
                    ("__name__", GAUGE_METRIC),
                    ("instance", &instance_label(g.instance_idx)),
                    (RUN_ID_LABEL, &self.run_id),
                    ("service", &service_label(g.service_idx)),
                    ("slot", &slot_label(g.slot_idx)),
                ]),
                buckets: self.bucket_span(0, last_idx),
            });
        }

        for c in &self.counters {
            out.push(DiscoverableSeries {
                labels: sorted_labels(&[
                    ("__name__", COUNTER_METRIC),
                    ("instance", &instance_label(c.instance_idx)),
                    (RUN_ID_LABEL, &self.run_id),
                    ("service", &service_label(c.service_idx)),
                ]),
                buckets: self.bucket_span(0, self.sample_count.saturating_sub(1)),
            });
        }

        for h in &self.histograms {
            let buckets = self.bucket_span(0, self.sample_count.saturating_sub(1));
            let instance = instance_label(h.instance_idx);
            let service = service_label(h.service_idx);
            let bucket_metric = histogram_bucket_metric_name();
            for i in 0..=self.histogram_bounds.len() {
                let le = if i < self.histogram_bounds.len() {
                    render_bound(self.histogram_bounds[i])
                } else {
                    render_bound(f64::INFINITY)
                };
                out.push(DiscoverableSeries {
                    labels: sorted_labels(&[
                        ("__name__", &bucket_metric),
                        ("instance", &instance),
                        ("le", &le),
                        (RUN_ID_LABEL, &self.run_id),
                        ("service", &service),
                    ]),
                    buckets: buckets.clone(),
                });
            }
            out.push(DiscoverableSeries {
                labels: sorted_labels(&[
                    ("__name__", &histogram_sum_metric_name()),
                    ("instance", &instance),
                    (RUN_ID_LABEL, &self.run_id),
                    ("service", &service),
                ]),
                buckets: buckets.clone(),
            });
            out.push(DiscoverableSeries {
                labels: sorted_labels(&[
                    ("__name__", &histogram_count_metric_name()),
                    ("instance", &instance),
                    (RUN_ID_LABEL, &self.run_id),
                    ("service", &service),
                ]),
                buckets,
            });
        }

        out
    }

    /// The set of distinct activity-bucket floors this corpus's real
    /// samples touch over `[first_idx, last_idx]` (inclusive, clamped to
    /// `sample_count`) — a series active continuously across a bucket
    /// boundary touches two buckets, one otherwise; [`ACTIVITY_BUCKET_MS`]
    /// (1h) is far larger than this corpus's own span, so in practice this
    /// is one or two entries, never computed as an assumption.
    fn bucket_span(&self, first_idx: usize, last_idx: usize) -> BTreeSet<i64> {
        let last_idx = last_idx.min(self.sample_count.saturating_sub(1));
        (first_idx..=last_idx)
            .map(|idx| activity_bucket(ts_ms(self, idx)))
            .collect()
    }
}

fn sorted_labels(pairs: &[(&str, &str)]) -> Vec<(String, String)> {
    let mut v: Vec<(String, String)> = pairs
        .iter()
        .map(|(k, val)| (k.to_string(), val.to_string()))
        .collect();
    v.sort();
    v
}

/// splitmix64 (public-domain mix; see `xtask/src/bench/dataset.rs`'s
/// identical constant/shape) — the sole PRNG primitive this generator
/// uses, always seeded from a deterministic combination of indices, never
/// threaded as mutable stream state (module doc comment).
fn splitmix64(mut x: u64) -> u64 {
    x = x.wrapping_add(0x9E37_79B9_7F4A_7C15);
    let mut z = x;
    z = (z ^ (z >> 30)).wrapping_mul(0xBF58_476D_1CE4_E5B9);
    z = (z ^ (z >> 27)).wrapping_mul(0x94D0_49BB_1331_11EB);
    z ^ (z >> 31)
}

/// Chains [`splitmix64`] over every element of `parts`, combined with
/// `seed` and a family-specific tag (the first element of `parts` by
/// convention below) — the deterministic "index tuple -> pseudo-random
/// u64" primitive every `*_value`/`*_bucket_counts` fn below is built on.
fn mix(seed: u64, parts: &[u64]) -> u64 {
    let mut acc = seed;
    for &p in parts {
        acc = splitmix64(acc ^ p);
    }
    acc
}

/// Every 6th gauge series (by flat generation order) goes stale — small
/// enough that the majority of the family stays fully populated (so
/// selectors/aggregations still have plenty of live data), large enough
/// that every representative selector in the query matrix
/// (`service="svc-3"`, `service=~"svc-(1|2)"`, ...) is guaranteed to
/// include at least one stale series.
const GAUGE_STALE_MODULUS: u64 = 6;
/// Every 5th counter series resets — an independent modulus from
/// [`GAUGE_STALE_MODULUS`] so the two staleness mechanisms don't always
/// land on the same flat index.
const COUNTER_RESET_MODULUS: u64 = 5;

/// Matches Prometheus's `--query.lookback-delta` default and PulsusDB's
/// `pulsus_promql::plan::DEFAULT_LOOKBACK_MS` (both 5 minutes) — used
/// only to time the engineered gauge staleness gap (issue #33 code
/// review, [medium]): a gap that never ages past the lookback by the
/// corpus's last evaluated timestamp is never actually excluded by
/// either engine's staleness rule, so "staleness as gaps" would never be
/// differentially exercised — both engines would just keep serving the
/// last real sample via lookback the whole time.
const LOOKBACK_MS: i64 = 300_000;

/// PulsusDB's activity-bucket size (`PULSUS_SERIES_ACTIVITY_BUCKET`
/// default, `pulsus_config::model::ReaderConfig::default`, docs/
/// schemas.md §2.1) — none of `deploy/e2e/compose.{single,cluster}.yaml`
/// override it, so this is exactly what the live stack uses. Used only to
/// compute the harness's own bucket-floor discovery expectation (issue
/// #33 architect adjudication, finding 2) — never to change ingestion or
/// query behavior.
pub const ACTIVITY_BUCKET_MS: i64 = 3_600_000;

/// `floor_to_activity_bucket` (`pulsus_model::floor_to_activity_bucket`),
/// duplicated rather than imported for the same "no internal-crate
/// dependency" reason as this module's other small wire-format/model
/// primitives (see `metrics.rs`'s `STALE_NAN_BITS` doc comment for the
/// precedent). Positive-only domain (this scenario's timestamps are
/// always real, recent Unix milliseconds — never negative), so plain
/// truncating integer division already matches ClickHouse's `intDiv`
/// (the two diverge only for negative operands).
pub fn activity_bucket(ms: i64) -> i64 {
    (ms / ACTIVITY_BUCKET_MS) * ACTIVITY_BUCKET_MS
}

/// Per-service gauge-value stride (issue #33 architect plan risk 4): large
/// enough that the maximum possible per-instance/slot offset+noise below
/// (bounded by `instances * 1000 + slots * 100 + 99`) can never approach
/// half this stride for any tier this generator is sized for — so
/// per-service sums/extrema can never cross between adjacent services.
/// `5e8` is also the literal threshold the pinned `> bool 5e8` query
/// matrix entry compares against (architect plan interfaces) — sized so
/// that threshold splits the (1-indexed) service range into a
/// non-degenerate true/false mix, not an all-or-nothing comparison.
const GAUGE_SERVICE_STRIDE: f64 = 2.0e8;
/// Per-service counter increment-rate stride, same rationale as
/// [`GAUGE_SERVICE_STRIDE`] but for the (per-sample) increment magnitude
/// rather than the cumulative value directly — the accumulated *sum*
/// across a service's instances inherits the same non-overlap guarantee
/// (see [`tests::per_service_gauge_and_counter_totals_are_strictly_ordered`]).
const COUNTER_SERVICE_STRIDE: f64 = 1000.0;

const GAUGE_TAG: u64 = 0xA1;
const COUNTER_TAG: u64 = 0xB2;
const HISTOGRAM_TAG: u64 = 0xC3;

/// This gauge series' value at `ts_idx` — the per-service stride (above)
/// plus a small, strictly-bounded per-instance/slot offset and a
/// deterministic noise term (`0..100`), pure in `(seed, g, ts_idx)`.
pub fn gauge_value(seed: u64, g: &GaugeSeries, ts_idx: usize) -> f64 {
    let base = (g.service_idx as f64 + 1.0) * GAUGE_SERVICE_STRIDE
        + g.instance_idx as f64 * 1000.0
        + g.slot_idx as f64 * 100.0;
    let noise = mix(
        seed,
        &[
            GAUGE_TAG,
            g.service_idx as u64,
            g.instance_idx as u64,
            g.slot_idx as u64,
            ts_idx as u64,
        ],
    ) % 100;
    base + noise as f64
}

/// This gauge series' emission state at `ts_idx`: `true` once `ts_idx`
/// reaches [`GaugeSeries::stale_from`] (never for a series with no
/// staleness engineered).
pub fn gauge_is_stale(g: &GaugeSeries, ts_idx: usize) -> bool {
    g.stale_from.is_some_and(|s| ts_idx >= s)
}

/// This counter series' per-sample increment at `ts_idx` — always
/// positive (a real counter only ever increases between resets), pure in
/// `(seed, c, ts_idx)`.
fn counter_increment(seed: u64, c: &CounterSeries, ts_idx: usize) -> f64 {
    let base_rate = (c.service_idx as f64 + 1.0) * COUNTER_SERVICE_STRIDE;
    let noise = mix(
        seed,
        &[
            COUNTER_TAG,
            c.service_idx as u64,
            c.instance_idx as u64,
            ts_idx as u64,
        ],
    ) % 50;
    base_rate + noise as f64
}

/// This counter series' cumulative value at `ts_idx`: the sum of every
/// increment since the last reset at-or-before `ts_idx` (`0.0` exactly at
/// the reset index itself — "value drops to 0", architect plan). Re-sums
/// from scratch on every call (module doc comment: no threaded RNG/running
/// -total state) — `sample_count` is small (tens), so this stays O(1) in
/// practice.
pub fn counter_value(seed: u64, c: &CounterSeries, ts_idx: usize) -> f64 {
    let start = match c.reset_at {
        Some(r) if ts_idx == r => return 0.0,
        Some(r) if ts_idx > r => r + 1,
        _ => 0,
    };
    (start..=ts_idx)
        .map(|k| counter_increment(seed, c, k))
        .sum()
}

/// This histogram data point's per-bucket-range *increment* at `ts_idx`
/// for bucket `bucket_idx` — every increment in `1..=10`, so a bucket's
/// running total (below) is always strictly increasing, pure in `(seed,
/// h, ts_idx, bucket_idx)`.
fn histogram_bucket_increment(
    seed: u64,
    h: &HistogramSeries,
    ts_idx: usize,
    bucket_idx: usize,
) -> u64 {
    1 + mix(
        seed,
        &[
            HISTOGRAM_TAG,
            h.service_idx as u64,
            h.instance_idx as u64,
            ts_idx as u64,
            bucket_idx as u64,
        ],
    ) % 10
}

/// This histogram data point's per-bucket-range counts at `ts_idx`
/// (`bounds_len + 1` entries — one per explicit bound, plus the implicit
/// `+Inf` overflow bucket the OTLP wire format always carries last) —
/// **cumulative since collection start** (OTLP `AggregationTemporality
/// ::CUMULATIVE` semantics, architect plan: "OTLP explicit-bucket
/// Histogram datapoints"), i.e. each bucket's own value across successive
/// `ts_idx` is monotonically non-decreasing, exactly like [`counter_value`]
/// — **not** an independent per-timestamp draw (an earlier version of this
/// fn was: live-run finding, issue #33 — feeding `rate()`/
/// `histogram_quantile` a bucket sequence that isn't actually cumulative
/// over time is invalid input under either engine's counter-reset
/// heuristics and produced spurious, engine-dependent divergences on
/// otherwise-correct code). Histograms have no staleness/resets
/// engineered (module doc comment), so this always accumulates from
/// `ts_idx == 0`, unconditionally. `bounds_len + 1` independent per-
/// timestamp increments feed each bucket's running total — see
/// [`histogram_bucket_increment`].
pub fn histogram_bucket_counts(
    seed: u64,
    h: &HistogramSeries,
    ts_idx: usize,
    bounds_len: usize,
) -> Vec<u64> {
    (0..=bounds_len)
        .map(|bucket_idx| {
            (0..=ts_idx)
                .map(|t| histogram_bucket_increment(seed, h, t, bucket_idx))
                .sum()
        })
        .collect()
}

/// A plausible (not physically meaningful — no invariant depends on it
/// beyond being finite and reproducible) `sum` for a histogram data point:
/// each bucket's count weighted by its bound-interval midpoint (the
/// overflow bucket weighted at `2x` the last finite bound).
fn histogram_sum(bounds: &[f64], counts: &[u64]) -> f64 {
    let mut total = 0.0;
    for (i, &c) in counts.iter().enumerate() {
        let mid = if i == 0 {
            bounds.first().copied().unwrap_or(0.0) / 2.0
        } else if i < bounds.len() {
            (bounds[i - 1] + bounds[i]) / 2.0
        } else {
            bounds.last().copied().unwrap_or(1.0) * 2.0
        };
        total += c as f64 * mid;
    }
    total
}

/// Renders a histogram bound the same way the collector's OTLP→PRW
/// conversion does — Go's shortest-round-trip decimal, matching Rust's
/// `f64` `Display` for finite values (same convention `pulsus-write::
/// protocols::otlp_metrics::render_bound` documents; duplicated here for
/// the same "no internal-crate dependency" reason as [`activity_bucket`]).
/// Used only by [`Corpus::discoverable_series`] to compute the expected
/// `le` label for each histogram bucket series.
fn render_bound(value: f64) -> String {
    if value.is_finite() {
        format!("{value}")
    } else {
        "+Inf".to_string()
    }
}

/// The sample index a deterministic subset of gauge series stop emitting
/// at, chosen so that the corpus's **last** evaluated timestamp (index
/// `sample_count - 1` — what every [`Mode::Instant`] query in the matrix
/// evaluates at, and the last step every [`Mode::Range`] query covers,
/// mirrors `metrics.rs`) lands strictly more than [`LOOKBACK_MS`] after
/// the gapped series' last real sample (issue #33 code review, [medium]):
/// a full extra step of headroom on top of the lookback boundary itself,
/// since the lookback window is left-open (`pulsus_promql::eval::
/// staleness`: a sample exactly `lookback_ms` old is still excluded, but
/// only just) — the margin must survive `step_ms` granularity, not land
/// exactly on the boundary. Falls back to "as early as possible" (index
/// `1`) when the window is too short to reach that margin at all (e.g. a
/// small synthetic corpus in this module's own unit tests) — those
/// corpora don't drive a live differential, so there is nothing to
/// preserve a lookback-crossing margin for.
fn stale_cutoff_for(sample_count: usize, step_ms: i64) -> usize {
    let max_idx = sample_count.saturating_sub(1);
    let lookback_samples = if step_ms > 0 {
        (LOOKBACK_MS / step_ms) as usize
    } else {
        0
    };
    max_idx
        .saturating_sub(lookback_samples + 1)
        .max(1)
        .min(max_idx.saturating_sub(1).max(1))
}

/// Builds every gauge/counter/histogram series identity for `spec`
/// (flat, deterministic generation order — [`GAUGE_STALE_MODULUS`]/
/// [`COUNTER_RESET_MODULUS`] key off this order), then derives the
/// completeness manifest (`expected_series`/`expected_samples`, issue #33
/// amendment) from them. Pure in `spec` (unit-tested determinism below).
pub fn generate(spec: &CorpusSpec) -> Corpus {
    let f = &spec.families;
    let stale_cutoff = stale_cutoff_for(spec.sample_count, spec.step_ms);
    let reset_at = (spec.sample_count / 2)
        .max(1)
        .min(spec.sample_count.saturating_sub(1).max(1));

    let mut gauges = Vec::with_capacity(f.services * f.gauge_instances * f.gauge_slots);
    let mut flat = 0u64;
    for service_idx in 0..f.services {
        for instance_idx in 0..f.gauge_instances {
            for slot_idx in 0..f.gauge_slots {
                let stale_from = flat
                    .is_multiple_of(GAUGE_STALE_MODULUS)
                    .then_some(stale_cutoff);
                gauges.push(GaugeSeries {
                    service_idx,
                    instance_idx,
                    slot_idx,
                    stale_from,
                });
                flat += 1;
            }
        }
    }

    let mut counters = Vec::with_capacity(f.services * f.counter_instances);
    let mut flat = 0u64;
    for service_idx in 0..f.services {
        for instance_idx in 0..f.counter_instances {
            let reset = flat
                .is_multiple_of(COUNTER_RESET_MODULUS)
                .then_some(reset_at);
            counters.push(CounterSeries {
                service_idx,
                instance_idx,
                reset_at: reset,
            });
            flat += 1;
        }
    }

    let mut histograms = Vec::with_capacity(f.services * f.histogram_instances);
    for service_idx in 0..f.services {
        for instance_idx in 0..f.histogram_instances {
            histograms.push(HistogramSeries {
                service_idx,
                instance_idx,
            });
        }
    }

    let bucket_series_per_histogram = spec.histogram_bounds.len() + 1; // + implicit +Inf
    let series_per_histogram = bucket_series_per_histogram + 2; // + _sum + _count

    let mut series =
        Vec::with_capacity(gauges.len() + counters.len() + histograms.len() * series_per_histogram);
    for g in &gauges {
        series.push(SeriesSpec {
            metric_name: GAUGE_METRIC.to_string(),
            samples_emitted: g.stale_from.unwrap_or(spec.sample_count),
        });
    }
    for _ in &counters {
        series.push(SeriesSpec {
            metric_name: COUNTER_METRIC.to_string(),
            samples_emitted: spec.sample_count,
        });
    }
    for _ in &histograms {
        for _ in 0..bucket_series_per_histogram {
            series.push(SeriesSpec {
                metric_name: histogram_bucket_metric_name(),
                samples_emitted: spec.sample_count,
            });
        }
        series.push(SeriesSpec {
            metric_name: histogram_sum_metric_name(),
            samples_emitted: spec.sample_count,
        });
        series.push(SeriesSpec {
            metric_name: histogram_count_metric_name(),
            samples_emitted: spec.sample_count,
        });
    }

    let expected_series = series.len();
    let expected_samples: usize = series.iter().map(|s| s.samples_emitted).sum();

    let first_ts_ms = spec.base_ms;
    let last_ts_ms = spec.base_ms + spec.step_ms * (spec.sample_count.saturating_sub(1) as i64);

    Corpus {
        run_id: spec.run_id.clone(),
        scale: spec.scale,
        seed: spec.seed,
        base_ms: spec.base_ms,
        step_ms: spec.step_ms,
        sample_count: spec.sample_count,
        gauges,
        counters,
        histograms,
        histogram_bounds: spec.histogram_bounds.clone(),
        series,
        expected_series,
        expected_samples,
        first_ts_ms,
        last_ts_ms,
    }
}

/// This corpus's `ts_idx`'th sample timestamp, milliseconds.
pub fn ts_ms(c: &Corpus, ts_idx: usize) -> i64 {
    c.base_ms + c.step_ms * ts_idx as i64
}

fn otlp_attr(key: &str, value: &str) -> serde_json::Value {
    serde_json::json!({ "key": key, "value": { "stringValue": value } })
}

/// Renders this corpus's `service_idx`'th service label value — `"svc-N"`,
/// matching the literal selectors the pinned query matrix uses
/// (`service="svc-3"`, `service=~"svc-(1|2)"`).
pub fn service_label(service_idx: usize) -> String {
    format!("svc-{service_idx}")
}

/// Renders an instance label value, zero-padded to 3 digits (`"inst-007"`)
/// so the pinned `instance!~"inst-0.*"` selector splits the population
/// into a non-degenerate matched/unmatched mix (instances `0..99` match,
/// the rest don't) rather than an all-or-nothing regex.
pub fn instance_label(instance_idx: usize) -> String {
    format!("inst-{instance_idx:03}")
}

pub fn slot_label(slot_idx: usize) -> String {
    format!("slot-{slot_idx}")
}

/// Builds this corpus's OTLP `ExportMetricsServiceRequest` JSON bodies,
/// **one per timestamp, in ascending order** (architect plan: "batched per
/// timestamp (≤ one timestamp-slice per request) ... in ascending
/// timestamp order (remote-write in-order requirement)"). Each request
/// carries at most three `Metric` descriptors (gauge/sum/histogram), each
/// with one data point per series that is live at that timestamp (a gauge
/// past its `stale_from` index contributes none — the OTLP-side
/// realization of a staleness gap).
pub fn to_otlp_export_requests(c: &Corpus) -> Vec<serde_json::Value> {
    (0..c.sample_count)
        .map(|ts_idx| build_request(c, ts_idx))
        .collect()
}

fn build_request(c: &Corpus, ts_idx: usize) -> serde_json::Value {
    let time_ns = ((ts_ms(c, ts_idx) as i128) * 1_000_000).to_string();

    let gauge_points: Vec<serde_json::Value> = c
        .gauges
        .iter()
        .filter(|g| !gauge_is_stale(g, ts_idx))
        .map(|g| {
            let attrs = vec![
                otlp_attr("service", &service_label(g.service_idx)),
                otlp_attr("instance", &instance_label(g.instance_idx)),
                otlp_attr("slot", &slot_label(g.slot_idx)),
                otlp_attr(RUN_ID_LABEL, &c.run_id),
            ];
            serde_json::json!({
                "attributes": attrs,
                "timeUnixNano": time_ns,
                "asDouble": gauge_value(c.seed, g, ts_idx),
            })
        })
        .collect();

    let counter_points: Vec<serde_json::Value> = c
        .counters
        .iter()
        .map(|cs| {
            let attrs = vec![
                otlp_attr("service", &service_label(cs.service_idx)),
                otlp_attr("instance", &instance_label(cs.instance_idx)),
                otlp_attr(RUN_ID_LABEL, &c.run_id),
            ];
            serde_json::json!({
                "attributes": attrs,
                "timeUnixNano": time_ns,
                "asDouble": counter_value(c.seed, cs, ts_idx),
            })
        })
        .collect();

    let histogram_points: Vec<serde_json::Value> = c
        .histograms
        .iter()
        .map(|h| {
            let counts = histogram_bucket_counts(c.seed, h, ts_idx, c.histogram_bounds.len());
            let count: u64 = counts.iter().sum();
            let sum = histogram_sum(&c.histogram_bounds, &counts);
            let attrs = vec![
                otlp_attr("service", &service_label(h.service_idx)),
                otlp_attr("instance", &instance_label(h.instance_idx)),
                otlp_attr(RUN_ID_LABEL, &c.run_id),
            ];
            serde_json::json!({
                "attributes": attrs,
                "timeUnixNano": time_ns,
                "count": count.to_string(),
                "sum": sum,
                "bucketCounts": counts.iter().map(u64::to_string).collect::<Vec<_>>(),
                "explicitBounds": c.histogram_bounds,
            })
        })
        .collect();

    let mut metrics = Vec::with_capacity(3);
    if !gauge_points.is_empty() {
        metrics.push(serde_json::json!({
            "name": GAUGE_METRIC,
            "unit": "By",
            "description": "issue #33 e2e differential gauge corpus",
            "gauge": { "dataPoints": gauge_points },
        }));
    }
    metrics.push(serde_json::json!({
        "name": COUNTER_METRIC,
        "unit": "1",
        "description": "issue #33 e2e differential counter corpus",
        "sum": {
            "dataPoints": counter_points,
            "aggregationTemporality": "AGGREGATION_TEMPORALITY_CUMULATIVE",
            "isMonotonic": true,
        },
    }));
    metrics.push(serde_json::json!({
        "name": HISTOGRAM_METRIC,
        "unit": "s",
        "description": "issue #33 e2e differential histogram corpus",
        "histogram": {
            "dataPoints": histogram_points,
            "aggregationTemporality": "AGGREGATION_TEMPORALITY_CUMULATIVE",
        },
    }));

    serde_json::json!({
        "resourceMetrics": [{
            "resource": { "attributes": [] },
            "scopeMetrics": [{ "metrics": metrics }],
        }]
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    fn small_families() -> FamilyCounts {
        FamilyCounts {
            services: 3,
            gauge_instances: 4,
            gauge_slots: 2,
            counter_instances: 5,
            histogram_instances: 2,
        }
    }

    fn spec(seed: u64) -> CorpusSpec {
        CorpusSpec {
            seed,
            scale: Scale::Ci,
            step_ms: 15_000,
            sample_count: 12,
            base_ms: 1_700_000_000_000,
            run_id: "e2e-metrics-test".to_string(),
            families: small_families(),
            histogram_bounds: vec![0.01, 0.1, 1.0],
        }
    }

    #[test]
    fn generate_is_deterministic_for_the_same_seed() {
        let a = to_otlp_export_requests(&generate(&spec(42)));
        let b = to_otlp_export_requests(&generate(&spec(42)));
        assert_eq!(a, b);
    }

    #[test]
    fn generate_differs_across_seeds() {
        let a = to_otlp_export_requests(&generate(&spec(1)));
        let b = to_otlp_export_requests(&generate(&spec(2)));
        assert_ne!(a, b);
    }

    #[test]
    fn expected_series_matches_the_flattened_series_count() {
        let c = generate(&spec(7));
        let f = small_families();
        let gauge_series = f.services * f.gauge_instances * f.gauge_slots;
        let counter_series = f.services * f.counter_instances;
        let series_per_hist = c.histogram_bounds.len() + 1 + 2;
        let hist_series = f.services * f.histogram_instances * series_per_hist;
        assert_eq!(
            c.expected_series,
            gauge_series + counter_series + hist_series
        );
        assert_eq!(c.series.len(), c.expected_series);
    }

    #[test]
    fn expected_samples_accounts_for_staleness_gaps_only_on_gauges() {
        let c = generate(&spec(7));
        // Every counter/histogram-derived series emits every sample; only
        // gauges (a `GAUGE_STALE_MODULUS`-th subset) gap early.
        let full_series = c
            .series
            .iter()
            .filter(|s| s.metric_name != GAUGE_METRIC)
            .count();
        let full_samples: usize = c
            .series
            .iter()
            .filter(|s| s.metric_name != GAUGE_METRIC)
            .map(|s| s.samples_emitted)
            .sum();
        assert_eq!(full_samples, full_series * c.sample_count);

        let stale_gauges = c.gauges.iter().filter(|g| g.stale_from.is_some()).count();
        assert!(
            stale_gauges > 0,
            "fixture must exercise at least one stale gauge"
        );
        let gauge_samples: usize = c
            .series
            .iter()
            .filter(|s| s.metric_name == GAUGE_METRIC)
            .map(|s| s.samples_emitted)
            .sum();
        assert!(gauge_samples < c.gauges.len() * c.sample_count);
    }

    #[test]
    fn full_scale_sums_to_approximately_ten_thousand_series() {
        // Mirrors the tier sizing `test/fixtures/metrics/differential.json`
        // ships (see that fixture's own comment) — pinned here too so a
        // future edit to either file surfaces a test failure rather than
        // silently drifting the "10k series" acceptance criterion.
        let full = FamilyCounts {
            services: 5,
            gauge_instances: 225,
            gauge_slots: 3,
            counter_instances: 680,
            histogram_instances: 58,
        };
        let s = CorpusSpec {
            seed: 1,
            scale: Scale::Full,
            step_ms: 15_000,
            sample_count: 40,
            base_ms: 0,
            run_id: "r".to_string(),
            families: full,
            histogram_bounds: vec![0.005, 0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 1.0],
        };
        let c = generate(&s);
        assert!(
            (9_000..=11_000).contains(&c.expected_series),
            "expected ~10k series, got {}",
            c.expected_series
        );
    }

    #[test]
    fn monotonic_except_at_reset() {
        let c = generate(&spec(7));
        for series in &c.counters {
            let mut prev: Option<f64> = None;
            for ts_idx in 0..c.sample_count {
                let v = counter_value(c.seed, series, ts_idx);
                if let Some(p) = prev {
                    let is_reset = series.reset_at == Some(ts_idx);
                    if is_reset {
                        assert_eq!(v, 0.0, "reset index must drop to exactly 0");
                    } else {
                        assert!(
                            v >= p,
                            "counter must be non-decreasing except at its reset index"
                        );
                    }
                }
                prev = Some(v);
            }
        }
    }

    /// Live-run finding, issue #33: histogram bucket counts must also be
    /// cumulative-over-time (strictly increasing per bucket across
    /// `ts_idx`, mirroring [`counter_value`]'s own invariant test) — an
    /// earlier version of [`histogram_bucket_counts`] drew an independent
    /// random value per timestamp, which is invalid `rate()`/
    /// `histogram_quantile` input (a "cumulative" counter that
    /// legitimately decreases has no real-world meaning) and produced a
    /// spurious, engine-dependent differential mismatch despite correct
    /// code on both sides.
    #[test]
    fn histogram_bucket_counts_are_cumulative_over_time() {
        let c = generate(&spec(9));
        let bounds_len = c.histogram_bounds.len();
        for h in &c.histograms {
            let mut prev: Option<Vec<u64>> = None;
            for ts_idx in 0..c.sample_count {
                let counts = histogram_bucket_counts(c.seed, h, ts_idx, bounds_len);
                assert_eq!(counts.len(), bounds_len + 1);
                if let Some(p) = &prev {
                    for (bucket_idx, (&prev_v, &v)) in p.iter().zip(&counts).enumerate() {
                        assert!(
                            v > prev_v,
                            "bucket {bucket_idx} must strictly increase over time: {prev_v} -> {v}"
                        );
                    }
                }
                prev = Some(counts);
            }
        }
    }

    /// Issue #33 architect plan risk 4: per-service aggregates (the
    /// underlying invariant `topk`/`bottomk`/comparison-operator query
    /// matrix entries rely on) must be strictly ordered by service index
    /// at every timestamp, for both families whose base value scales with
    /// service index.
    #[test]
    fn per_service_gauge_and_counter_totals_are_strictly_ordered() {
        let c = generate(&spec(11));
        let f = small_families();
        for ts_idx in [0, c.sample_count / 2, c.sample_count - 1] {
            let mut gauge_totals = Vec::new();
            let mut counter_totals = Vec::new();
            for service_idx in 0..f.services {
                let gauge_total: f64 = c
                    .gauges
                    .iter()
                    .filter(|g| g.service_idx == service_idx && !gauge_is_stale(g, ts_idx))
                    .map(|g| gauge_value(c.seed, g, ts_idx))
                    .sum();
                gauge_totals.push(gauge_total);
                let counter_total: f64 = c
                    .counters
                    .iter()
                    .filter(|cs| cs.service_idx == service_idx)
                    .map(|cs| counter_value(c.seed, cs, ts_idx))
                    .sum();
                counter_totals.push(counter_total);
            }
            for w in gauge_totals.windows(2) {
                assert!(
                    w[0] < w[1],
                    "gauge per-service totals must be strictly increasing: {gauge_totals:?}"
                );
            }
            for w in counter_totals.windows(2) {
                assert!(
                    w[0] < w[1],
                    "counter per-service totals must be strictly increasing: {counter_totals:?}"
                );
            }
        }
    }

    #[test]
    fn to_otlp_export_requests_is_ascending_and_one_per_timestamp() {
        let c = generate(&spec(3));
        let requests = to_otlp_export_requests(&c);
        assert_eq!(requests.len(), c.sample_count);
        let mut prev_ts: Option<i64> = None;
        for (ts_idx, req) in requests.iter().enumerate() {
            let metrics = req["resourceMetrics"][0]["scopeMetrics"][0]["metrics"]
                .as_array()
                .unwrap();
            let sum_metric = metrics
                .iter()
                .find(|m| m["name"] == COUNTER_METRIC)
                .unwrap();
            let dp = &sum_metric["sum"]["dataPoints"][0];
            let ts: i64 = dp["timeUnixNano"]
                .as_str()
                .unwrap()
                .parse::<i128>()
                .unwrap() as i64
                / 1_000_000;
            assert_eq!(ts, ts_ms(&c, ts_idx));
            if let Some(prev) = prev_ts {
                assert!(
                    ts > prev,
                    "timestamps must be strictly ascending across requests"
                );
            }
            prev_ts = Some(ts);
        }
    }

    #[test]
    fn stale_gauge_stops_appearing_in_later_requests() {
        let c = generate(&spec(3));
        let stale_series = c
            .gauges
            .iter()
            .find(|g| g.stale_from.is_some())
            .expect("fixture engineers at least one stale gauge");
        let stale_from = stale_series.stale_from.unwrap();
        let requests = to_otlp_export_requests(&c);
        let last_ts_idx = c.sample_count - 1;
        assert!(
            stale_from < last_ts_idx,
            "test needs a gap before the final sample"
        );

        let count_gauge_points = |req: &serde_json::Value| -> usize {
            req["resourceMetrics"][0]["scopeMetrics"][0]["metrics"]
                .as_array()
                .unwrap()
                .iter()
                .find(|m| m["name"] == GAUGE_METRIC)
                .map(|m| m["gauge"]["dataPoints"].as_array().unwrap().len())
                .unwrap_or(0)
        };
        let before = count_gauge_points(&requests[stale_from - 1]);
        let after = count_gauge_points(&requests[stale_from]);
        assert!(
            after < before,
            "gauge point count must drop once a series goes stale"
        );
    }

    /// Issue #33 code review, [medium]: the engineered gauge staleness
    /// gap must age past [`LOOKBACK_MS`] by the corpus's own last
    /// evaluated timestamp (`metrics.rs`'s `run_query_matrix` evaluates
    /// every `Mode::Instant` entry at `corpus.last_ts_ms`, and every
    /// `Mode::Range` entry's last step lands there too) — otherwise
    /// neither engine's lookback ever actually excludes the "stale"
    /// series, and staleness-as-gaps is never differentially exercised.
    /// Uses the real fixture's shape (`test/fixtures/metrics/
    /// differential.json`'s pinned `step_ms`/`sample_count`), not the
    /// tiny synthetic [`spec`] helper above (12 samples * 15s = 165s
    /// total window — shorter than the 300s lookback itself, so no
    /// cutoff placement could ever cross it).
    #[test]
    fn stale_gauge_gap_ages_past_the_lookback_boundary_by_the_last_evaluated_timestamp() {
        let s = CorpusSpec {
            seed: 11,
            scale: Scale::Ci,
            step_ms: 15_000,
            sample_count: 40,
            base_ms: 0,
            run_id: "r".to_string(),
            families: small_families(),
            histogram_bounds: vec![0.01, 0.1, 1.0],
        };
        let c = generate(&s);
        let stale_series = c
            .gauges
            .iter()
            .find(|g| g.stale_from.is_some())
            .expect("fixture engineers at least one stale gauge");
        let stale_from = stale_series.stale_from.unwrap();
        assert!(
            stale_from >= 1,
            "a gap needs at least one real sample before it"
        );

        let last_real_sample_ts = ts_ms(&c, stale_from - 1);
        let last_evaluated_ts = c.last_ts_ms; // == ts_ms(&c, c.sample_count - 1)
        let gap_age_ms = last_evaluated_ts - last_real_sample_ts;
        assert!(
            gap_age_ms > LOOKBACK_MS,
            "gap age {gap_age_ms}ms (stale_from={stale_from}) must exceed the {LOOKBACK_MS}ms \
             lookback boundary by the corpus's last evaluated timestamp — otherwise the gap is \
             never actually excluded by either engine's staleness rule"
        );
    }

    // -- discoverable_series (issue #33 architect adjudication, finding 2) --

    #[test]
    fn activity_bucket_floors_to_the_configured_size() {
        assert_eq!(activity_bucket(3_600_001), 3_600_000);
        assert_eq!(activity_bucket(7_199_999), 3_600_000);
        assert_eq!(activity_bucket(3_600_000), 3_600_000);
        assert_eq!(activity_bucket(0), 0);
    }

    #[test]
    fn discoverable_series_count_matches_expected_series() {
        let c = generate(&spec(13));
        assert_eq!(c.discoverable_series().len(), c.expected_series);
    }

    #[test]
    fn discoverable_series_every_entry_has_a_name_and_run_id_label() {
        let c = generate(&spec(13));
        for d in c.discoverable_series() {
            let names: Vec<&str> = d.labels.iter().map(|(k, _)| k.as_str()).collect();
            assert!(names.contains(&"__name__"), "{d:?} missing __name__");
            assert!(
                names.contains(&RUN_ID_LABEL),
                "{d:?} missing {RUN_ID_LABEL}"
            );
            assert!(
                !d.buckets.is_empty(),
                "{d:?} touches no activity bucket at all"
            );
        }
    }

    /// A stale gauge's discoverable buckets must reflect only its *real*
    /// samples (`0..stale_from`), never the corpus's full span — the same
    /// invariant [`stale_gauge_stops_appearing_in_later_requests`] checks
    /// at the OTLP-payload level, checked here at the discovery-manifest
    /// level.
    #[test]
    fn discoverable_series_stale_gauge_buckets_stop_at_its_last_real_sample() {
        let c = generate(&spec(13));
        let stale = c
            .gauges
            .iter()
            .find(|g| g.stale_from.is_some())
            .expect("fixture engineers at least one stale gauge");
        let live = c
            .gauges
            .iter()
            .find(|g| g.stale_from.is_none())
            .expect("fixture engineers at least one still-live gauge");

        let discoverable = c.discoverable_series();
        let stale_labels = sorted_labels(&[
            ("__name__", GAUGE_METRIC),
            ("instance", &instance_label(stale.instance_idx)),
            (RUN_ID_LABEL, &c.run_id),
            ("service", &service_label(stale.service_idx)),
            ("slot", &slot_label(stale.slot_idx)),
        ]);
        let live_labels = sorted_labels(&[
            ("__name__", GAUGE_METRIC),
            ("instance", &instance_label(live.instance_idx)),
            (RUN_ID_LABEL, &c.run_id),
            ("service", &service_label(live.service_idx)),
            ("slot", &slot_label(live.slot_idx)),
        ]);
        let stale_buckets = &discoverable
            .iter()
            .find(|d| d.labels == stale_labels)
            .unwrap()
            .buckets;
        let live_buckets = &discoverable
            .iter()
            .find(|d| d.labels == live_labels)
            .unwrap()
            .buckets;

        let expected_stale_buckets = c.bucket_span(0, stale.stale_from.unwrap() - 1);
        let expected_live_buckets = c.bucket_span(0, c.sample_count - 1);
        assert_eq!(stale_buckets, &expected_stale_buckets);
        assert_eq!(live_buckets, &expected_live_buckets);
    }

    #[test]
    fn discoverable_series_histogram_bucket_le_values_include_plus_inf() {
        let c = generate(&spec(13));
        let h = &c.histograms[0];
        let instance = instance_label(h.instance_idx);
        let service = service_label(h.service_idx);
        let les: BTreeSet<String> = c
            .discoverable_series()
            .into_iter()
            .filter(|d| {
                d.labels
                    .contains(&("__name__".to_string(), histogram_bucket_metric_name()))
                    && d.labels
                        .contains(&("instance".to_string(), instance.clone()))
                    && d.labels.contains(&("service".to_string(), service.clone()))
            })
            .filter_map(|d| {
                d.labels
                    .iter()
                    .find(|(k, _)| k == "le")
                    .map(|(_, v)| v.clone())
            })
            .collect();
        assert!(les.contains("+Inf"), "expected a +Inf bucket, got {les:?}");
        assert_eq!(les.len(), c.histogram_bounds.len() + 1);
    }
}
