// @generated by the Go extractor in this file's doc comment.
//
// DO NOT EDIT BY HAND. Issue #400 Stage 2.

//! Every Unicode property name grafana/loki v3.7.4's vendored regexp
//! parser accepts in a `\p{…}` / `\P{…}` / `\pL` class, and nothing else.
//!
//! # The rule this table IS
//!
//! `unicodeTable`
//! (`vendor/github.com/grafana/regexp/syntax/parse.go:1646-1658 @ v3.7.4`)
//! is exactly three lookups and no fourth:
//!
//! ```text
//! if name == "Any" { return anyTable, anyTable }
//! if t := unicode.Categories[name]; t != nil { … }
//! if t := unicode.Scripts[name]; t != nil { … }
//! return nil, nil                       // -> ErrInvalidCharRange, parse.go:1707
//! ```
//!
//! There is no `canonicalName`, no case folding of the NAME, and no
//! PCRE-style alias set — which is why `\p{LC}` is served (it is a
//! `unicode.Categories` key) and `\p{Lc}` is a 400, and why
//! `\p{Alphabetic}`, `\p{Assigned}`, `\p{Ascii}`, `\p{ASCII}`,
//! `\p{Word}`, `\p{Uppercase_Letter}` and `\p{Letter}` — all of which
//! the Rust `regex` crate accepts — are 400s there.
//!
//! A leading `^` is NOT part of the name: `parse.go:1698-1701 @ v3.7.4`
//! strips it and flips the sign before the lookup, so `\p{^L}` is
//! `\P{L}` and is SERVED. [`is_go_unicode_property_name`] therefore
//! takes the name with the `^` already removed; see
//! [`crate::re2_definitely_rejects`], whose rule (f) does the stripping.
//!
//! # Regeneration
//!
//! ```text
//! # go.mod: module gen / go 1.25
//! cat > main.go <<'EOF'
//! package main
//!
//! import ("fmt"; "sort"; "unicode")
//!
//! func main() {
//!     set := map[string]bool{"Any": true}
//!     for k := range unicode.Categories { set[k] = true }
//!     for k := range unicode.Scripts { set[k] = true }
//!     names := make([]string, 0, len(set))
//!     for k := range set { names = append(names, k) }
//!     sort.Strings(names)
//!     fmt.Printf("// categories=%d scripts=%d total=%d unicode=%s\n",
//!         len(unicode.Categories), len(unicode.Scripts), len(names), unicode.Version)
//!     for _, n := range names { fmt.Printf("    %q,\n", n) }
//! }
//! EOF
//! go run .
//! ```
//!
//! **EXTRACTION toolchain: `go1.25.5`** (`go version` on this machine,
//! 2026-08-12), which printed `categories=38 scripts=163 total=202
//! unicode=15.0.0`. **REFERENCE toolchain: `go1.26.5`** (`go.mod @
//! b318f282`, the `go` directive). The extraction toolchain is
//! incidental — it is named only so the extraction is reproducible.
//!
//! **What makes the table right is not the toolchain, it is the probe.**
//! All 202 names below were put to the pinned container individually
//! (`grafana/loki@sha256:87f0a067…` on `ci/logql/config.yaml`,
//! `pulsus-c400-loki`, port 13400, 2026-08-12) at
//! `{app="x"} | line_format "{{ __line__ }}" |~ "\p{NAME}"`:
//! **202 accepted, 0 rejected**, in 86 s. The two toolchains are
//! therefore MEASURED to agree on this set rather than assumed to.
//! `tests/re2_reject_classes.rs`'s `the_202_name_table_is_the_forks`
//! keeps the live re-probe as an `#[ignore]`d helper and asserts the
//! count plus the discriminators hermetically.

/// The 202 names, sorted, as the Go extractor emitted them.
static GO_UNICODE_PROPERTY_NAMES: &[&str] = &[
    "Adlam",
    "Ahom",
    "Anatolian_Hieroglyphs",
    "Any",
    "Arabic",
    "Armenian",
    "Avestan",
    "Balinese",
    "Bamum",
    "Bassa_Vah",
    "Batak",
    "Bengali",
    "Bhaiksuki",
    "Bopomofo",
    "Brahmi",
    "Braille",
    "Buginese",
    "Buhid",
    "C",
    "Canadian_Aboriginal",
    "Carian",
    "Caucasian_Albanian",
    "Cc",
    "Cf",
    "Chakma",
    "Cham",
    "Cherokee",
    "Chorasmian",
    "Cn",
    "Co",
    "Common",
    "Coptic",
    "Cs",
    "Cuneiform",
    "Cypriot",
    "Cypro_Minoan",
    "Cyrillic",
    "Deseret",
    "Devanagari",
    "Dives_Akuru",
    "Dogra",
    "Duployan",
    "Egyptian_Hieroglyphs",
    "Elbasan",
    "Elymaic",
    "Ethiopic",
    "Georgian",
    "Glagolitic",
    "Gothic",
    "Grantha",
    "Greek",
    "Gujarati",
    "Gunjala_Gondi",
    "Gurmukhi",
    "Han",
    "Hangul",
    "Hanifi_Rohingya",
    "Hanunoo",
    "Hatran",
    "Hebrew",
    "Hiragana",
    "Imperial_Aramaic",
    "Inherited",
    "Inscriptional_Pahlavi",
    "Inscriptional_Parthian",
    "Javanese",
    "Kaithi",
    "Kannada",
    "Katakana",
    "Kawi",
    "Kayah_Li",
    "Kharoshthi",
    "Khitan_Small_Script",
    "Khmer",
    "Khojki",
    "Khudawadi",
    "L",
    "LC",
    "Lao",
    "Latin",
    "Lepcha",
    "Limbu",
    "Linear_A",
    "Linear_B",
    "Lisu",
    "Ll",
    "Lm",
    "Lo",
    "Lt",
    "Lu",
    "Lycian",
    "Lydian",
    "M",
    "Mahajani",
    "Makasar",
    "Malayalam",
    "Mandaic",
    "Manichaean",
    "Marchen",
    "Masaram_Gondi",
    "Mc",
    "Me",
    "Medefaidrin",
    "Meetei_Mayek",
    "Mende_Kikakui",
    "Meroitic_Cursive",
    "Meroitic_Hieroglyphs",
    "Miao",
    "Mn",
    "Modi",
    "Mongolian",
    "Mro",
    "Multani",
    "Myanmar",
    "N",
    "Nabataean",
    "Nag_Mundari",
    "Nandinagari",
    "Nd",
    "New_Tai_Lue",
    "Newa",
    "Nko",
    "Nl",
    "No",
    "Nushu",
    "Nyiakeng_Puachue_Hmong",
    "Ogham",
    "Ol_Chiki",
    "Old_Hungarian",
    "Old_Italic",
    "Old_North_Arabian",
    "Old_Permic",
    "Old_Persian",
    "Old_Sogdian",
    "Old_South_Arabian",
    "Old_Turkic",
    "Old_Uyghur",
    "Oriya",
    "Osage",
    "Osmanya",
    "P",
    "Pahawh_Hmong",
    "Palmyrene",
    "Pau_Cin_Hau",
    "Pc",
    "Pd",
    "Pe",
    "Pf",
    "Phags_Pa",
    "Phoenician",
    "Pi",
    "Po",
    "Ps",
    "Psalter_Pahlavi",
    "Rejang",
    "Runic",
    "S",
    "Samaritan",
    "Saurashtra",
    "Sc",
    "Sharada",
    "Shavian",
    "Siddham",
    "SignWriting",
    "Sinhala",
    "Sk",
    "Sm",
    "So",
    "Sogdian",
    "Sora_Sompeng",
    "Soyombo",
    "Sundanese",
    "Syloti_Nagri",
    "Syriac",
    "Tagalog",
    "Tagbanwa",
    "Tai_Le",
    "Tai_Tham",
    "Tai_Viet",
    "Takri",
    "Tamil",
    "Tangsa",
    "Tangut",
    "Telugu",
    "Thaana",
    "Thai",
    "Tibetan",
    "Tifinagh",
    "Tirhuta",
    "Toto",
    "Ugaritic",
    "Vai",
    "Vithkuqi",
    "Wancho",
    "Warang_Citi",
    "Yezidi",
    "Yi",
    "Z",
    "Zanabazar_Square",
    "Zl",
    "Zp",
    "Zs",
];

/// `true` when `name` is one `unicodeTable` resolves — i.e. the reference
/// accepts `\p{name}`. `name` must already have any leading `^`
/// stripped (see the module doc).
///
/// Binary search over a sorted static: no allocation, and the sortedness
/// is asserted by `the_table_is_sorted_and_deduplicated`.
#[must_use]
pub fn is_go_unicode_property_name(name: &str) -> bool {
    GO_UNICODE_PROPERTY_NAMES.binary_search(&name).is_ok()
}

/// How many names the reference accepts. A future Go toolchain adding a
/// script moves this, which reddens
/// `tests/re2_reject_classes.rs`'s count assertion.
#[must_use]
pub fn go_unicode_property_name_count() -> usize {
    GO_UNICODE_PROPERTY_NAMES.len()
}

/// The whole table, for the `#[ignore]`d live re-probe helper.
#[must_use]
pub fn go_unicode_property_names() -> &'static [&'static str] {
    GO_UNICODE_PROPERTY_NAMES
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The binary search's premise. A hand edit that breaks the order
    /// would make `is_go_unicode_property_name` answer `false` for a
    /// name that IS in the table — a false rejection, the harmful
    /// direction.
    #[test]
    fn the_table_is_sorted_and_deduplicated() {
        let names = go_unicode_property_names();
        for w in names.windows(2) {
            assert!(w[0] < w[1], "{:?} must sort before {:?}", w[0], w[1]);
        }
    }
}
