//! Serializes `cargo xtask bench metrics-labels`'s evidence to JSON
//! (`docs/benchmarks/data/*.json`) and renders a markdown table body
//! suitable for pasting into `docs/benchmarks/m2-metrics-label-resolution.md`
//! — mirrors `super::super::report`'s (issue #16) shape and UNVALIDATED
//! honesty for the same two-tier evidence model (docs/schemas.md §9): every
//! wall-clock/`system.query_log` number here is scale-dependent and
//! recorded, never gated. [`OverInclusion`] carries **two** ratios (issue
//! #34 CODE review round-2 [valid] finding #5) — see its own doc comment
//! for which one is the scale-invariant, Tier-1 claim.
//!
//! **Mechanical consistency (issue #34 CODE review round-2 item 4).** This
//! module's own `consistency_tests` submodule loads the *committed*
//! `docs/benchmarks/data/metrics-labels-ci.json` and asserts the report
//! doc's comparative *claims* against it directly. Scope, precisely
//! (round-3 [low] finding #4): this asserts claims, not bytes — a future
//! regeneration whose numbers drift but preserve every stated conclusion
//! (a win/loss split, a ratio's saturation point) passes; a regeneration
//! that flips a stated conclusion fails `cargo test` instead of silently
//! rotting (the exact failure mode two prior review rounds on this issue
//! caught only by hand). It is not a literal diff against the markdown
//! doc's prose or table values — see `consistency_tests`' own doc comment.

use crate::bench::Profile;

use super::corpus::MetricsCorpusSummary;
use super::idx::IdxSummary;
use super::paths::{PathEvidence, RefreshEvidence};

/// One activity-bucket size's full pass: corpus + idx build + all three
/// paths' evidence + refresh-sweep evidence.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct BucketReport {
    pub bucket_ms: i64,
    pub corpus: MetricsCorpusSummary,
    pub idx: IdxSummary,
    pub paths: Vec<PathEvidence>,
    pub refresh: Vec<RefreshEvidence>,
}

/// The day-bucket over-inclusion evidence, **two** ratios (issue #34 CODE
/// review round-2 [valid] finding #5 — round-1 captured only `read_rows`,
/// which the structural primary-key finding already fully explains and
/// which is therefore uninformative about §2.1's actual claim):
/// - `ratio` (`read_rows_1d / read_rows_1h`) — the **physical** read cost.
///   Scale-invariant and Tier-1, but explained entirely by
///   `metric_series`'s `(metric_name, fingerprint, unix_milli)` primary key
///   never pruning by time once fingerprint cardinality is non-trivial
///   (`paths.rs`'s module doc comment) — expect `≈1.0` regardless of bucket
///   size, not `>1`.
/// - `candidate_ratio` (`matched_candidates_1d / matched_candidates_1h`) —
///   the **semantic** over-inclusion docs/schemas.md §2.1 actually
///   describes ("a 10-minute historical query against a `1d` bucket drags
///   that whole day's series … through label matching"): with this
///   corpus's single-bucket-per-series staggering, a 10-minute window
///   floored to a `1h` bucket matches only the series staggered into that
///   one bucket (~`C / buckets.len()`), while floored to a `1d` bucket (few
///   or one bucket total) it matches nearly the whole metric's `C` series —
///   a materially larger ratio, and the one this benchmark can actually
///   demonstrate at CI scale.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct OverInclusion {
    pub cardinality: u64,
    pub read_rows_1h: u64,
    pub read_rows_1d: u64,
    /// `read_rows_1d / read_rows_1h` — see the struct doc comment. `0.0` if
    /// `read_rows_1h == 0` (degenerate, should not occur on a non-empty
    /// corpus).
    pub ratio: f64,
    /// Deduplicated matched-fingerprint count for the same probe query,
    /// `1h` bucket size.
    pub matched_candidates_1h: u64,
    /// Same, `1d` bucket size.
    pub matched_candidates_1d: u64,
    /// `matched_candidates_1d / matched_candidates_1h` — see the struct doc
    /// comment. `0.0` if `matched_candidates_1h == 0`.
    pub candidate_ratio: f64,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct MetricsLabelsReport {
    pub profile: Profile,
    pub seed: u64,
    pub dist: bool,
    pub cluster: Option<String>,
    pub cardinalities: Vec<u64>,
    pub buckets: Vec<BucketReport>,
    pub over_inclusion: Vec<OverInclusion>,
}

/// Renders the per-path/per-tier/per-selector evidence table, the
/// refresh-sweep table, and the over-inclusion table (both ratios). Every
/// row is rendered — curation of which rows map to a §9 target happens in
/// the committed report doc, not here (same division of labour as
/// `super::super::report::render_markdown`).
pub fn render_markdown(report: &MetricsLabelsReport) -> String {
    let mut out = String::new();
    out.push_str(&format!(
        "<!-- generated by `cargo xtask bench metrics-labels` (profile={:?}, seed={}, dist={}) -->\n",
        report.profile, report.seed, report.dist
    ));
    out.push_str(&format!(
        "Cardinalities: {:?}. Buckets: {:?}.\n\n",
        report.cardinalities,
        report
            .buckets
            .iter()
            .map(|b| b.bucket_ms)
            .collect::<Vec<_>>()
    ));

    out.push_str(
        "| bucket_ms | path | metric | cardinality | selector | matched_series | wall p50 (ms) | \
         wall p95 (ms) | wall p99 (ms) | read_rows | selected/total marks | read_bytes | memory_usage |\n",
    );
    out.push_str("|---|---|---|---|---|---|---|---|---|---|---|---|---|\n");
    for bucket in &report.buckets {
        for p in &bucket.paths {
            out.push_str(&format!(
                "| {} | {} | {} | {} | {} | {} | {:.4} | {:.4} | {:.4} | {} | {}/{} | {} | {} |\n",
                bucket.bucket_ms,
                p.path,
                p.metric_name,
                p.cardinality,
                p.selector,
                p.matched_series,
                p.wall_ms_p50,
                p.wall_ms_p95,
                p.wall_ms_p99,
                p.read_rows,
                p.selected_marks,
                p.total_marks,
                p.read_bytes,
                p.memory_usage,
            ));
        }
    }

    out.push_str(
        "\n| bucket_ms | kind | resident_series | oversize | wall_ms | read_rows | read_bytes | \
         selected_marks | memory_usage | query_duration_ms |\n",
    );
    out.push_str("|---|---|---|---|---|---|---|---|---|---|\n");
    for bucket in &report.buckets {
        for r in &bucket.refresh {
            out.push_str(&format!(
                "| {} | {} | {} | {} | {:.2} | {} | {} | {} | {} | {} |\n",
                r.bucket_ms,
                r.kind,
                r.resident_series,
                r.oversize,
                r.wall_ms,
                r.read_rows,
                r.read_bytes,
                r.selected_marks,
                r.memory_usage,
                r.query_duration_ms,
            ));
        }
    }

    out.push_str(
        "\n| cardinality | read_rows (1h) | read_rows (1d) | read_rows ratio (1d/1h) | \
         matched_candidates (1h) | matched_candidates (1d) | candidate ratio (1d/1h) |\n",
    );
    out.push_str("|---|---|---|---|---|---|---|\n");
    for o in &report.over_inclusion {
        out.push_str(&format!(
            "| {} | {} | {} | {:.2} | {} | {} | {:.2} |\n",
            o.cardinality,
            o.read_rows_1h,
            o.read_rows_1d,
            o.ratio,
            o.matched_candidates_1h,
            o.matched_candidates_1d,
            o.candidate_ratio,
        ));
    }

    out.push_str(
        "\n| bucket_ms | metric | build_ms | rows | bytes_on_disk |\n|---|---|---|---|---|\n",
    );
    for bucket in &report.buckets {
        out.push_str(&format!(
            "| {} | metric_series_idx (all tiers) | {} | {} | {} |\n",
            bucket.bucket_ms, bucket.idx.build_ms, bucket.idx.rows, bucket.idx.bytes_on_disk
        ));
    }

    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::bench::metrics_labels::corpus::TierInfo;

    fn sample_report() -> MetricsLabelsReport {
        MetricsLabelsReport {
            profile: Profile::Ci,
            seed: 1,
            dist: false,
            cluster: None,
            cardinalities: vec![1_000],
            buckets: vec![BucketReport {
                bucket_ms: 3_600_000,
                corpus: MetricsCorpusSummary {
                    tiers: vec![TierInfo {
                        metric_name: "metric_1000".to_string(),
                        cardinality: 1_000,
                        series_rows: 1_000,
                        narrow_fp: 42,
                    }],
                    total_series_rows: 24_000,
                    bucket_ms: 3_600_000,
                    window_ms: 86_400_000,
                    end_ms: 1_000_000,
                    load_elapsed_ms: 5,
                },
                idx: IdxSummary {
                    build_ms: 10,
                    rows: 5_000,
                    bytes_on_disk: 1_234,
                },
                paths: vec![PathEvidence {
                    path: "cache".to_string(),
                    metric_name: "metric_1000".to_string(),
                    cardinality: 1_000,
                    selector: r#"job="j0""#.to_string(),
                    matched_series: 125,
                    wall_ms_p50: 0.01,
                    wall_ms_p95: 0.02,
                    wall_ms_p99: 0.03,
                    read_rows: 0,
                    read_bytes: 0,
                    selected_marks: 0,
                    total_marks: 0,
                    memory_usage: 0,
                    query_duration_ms: 0,
                    explain_indexes: vec![],
                }],
                refresh: vec![RefreshEvidence {
                    bucket_ms: 3_600_000,
                    kind: "full_sweep".to_string(),
                    resident_series: 1_000,
                    oversize: false,
                    wall_ms: 12.0,
                    read_rows: 24_000,
                    read_bytes: 100,
                    selected_marks: 1,
                    memory_usage: 200,
                    query_duration_ms: 5,
                }],
            }],
            over_inclusion: vec![OverInclusion {
                cardinality: 1_000,
                read_rows_1h: 10,
                read_rows_1d: 40,
                ratio: 4.0,
                matched_candidates_1h: 5,
                matched_candidates_1d: 100,
                candidate_ratio: 20.0,
            }],
        }
    }

    #[test]
    fn render_markdown_includes_every_path_row() {
        let md = render_markdown(&sample_report());
        assert!(md.contains("metric_1000"));
        assert!(md.contains("cache"));
    }

    #[test]
    fn render_markdown_includes_both_over_inclusion_ratios() {
        let md = render_markdown(&sample_report());
        assert!(md.contains("4.00"));
        assert!(md.contains("20.00"));
    }

    #[test]
    fn metrics_labels_report_serializes_to_json() {
        let json = serde_json::to_string(&sample_report()).expect("serializes");
        assert!(json.contains("\"metric_1000\""));
    }

    #[test]
    fn metrics_labels_report_round_trips_through_json() {
        let json = serde_json::to_string(&sample_report()).expect("serializes");
        let back: MetricsLabelsReport = serde_json::from_str(&json).expect("deserializes");
        assert_eq!(back.over_inclusion[0].candidate_ratio, 20.0);
    }
}

/// Mechanical consistency test (issue #34 CODE review round-2, item 4).
///
/// **Honest scope (round-3 [low] finding #4):** this asserts the report's
/// comparative *claims* against the committed **JSON** evidence
/// (`docs/benchmarks/data/metrics-labels-ci.json`) — it is not a literal
/// diff against `docs/benchmarks/m2-metrics-label-resolution.md`'s prose or
/// tables, and cannot catch a hand-transcription typo in the markdown that
/// still happens to agree with these assertions' *conclusions* (e.g. "idx
/// wins" stated correctly but with a wrong millisecond figure quoted next
/// to it). What it *does* catch, which is the failure mode that actually
/// occurred across this issue's review rounds: a future regeneration that
/// changes the underlying numbers enough to flip a stated conclusion (a
/// win/loss split, a ratio's saturation point, a materiality threshold)
/// without the prose being updated to match. Reads a real file (not a live
/// database), so this runs in the ordinary `cargo test -p xtask` pass, no
/// `PULSUS_TEST_CLICKHOUSE` gate needed.
#[cfg(test)]
mod consistency_tests {
    use super::*;

    fn load_committed_report() -> MetricsLabelsReport {
        // `CARGO_MANIFEST_DIR` for this crate is `<repo>/xtask`; the
        // committed artifact lives at `<repo>/docs/benchmarks/data/...`.
        let path = concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/../docs/benchmarks/data/metrics-labels-ci.json"
        );
        let json = std::fs::read_to_string(path).unwrap_or_else(|e| {
            panic!(
                "failed to read the committed evidence artifact at {path}: {e} — this test \
                 asserts the m2-metrics-label-resolution.md report's comparative claims against \
                 it; regenerate via `cargo xtask bench metrics-labels --profile ci` if it is \
                 genuinely missing"
            )
        });
        serde_json::from_str(&json).unwrap_or_else(|e| {
            panic!("failed to deserialize the committed evidence artifact at {path}: {e}")
        })
    }

    fn find<'a>(
        report: &'a MetricsLabelsReport,
        bucket_ms: i64,
        path: &str,
        cardinality: u64,
        selector_substr: &str,
    ) -> &'a PathEvidence {
        report
            .buckets
            .iter()
            .find(|b| b.bucket_ms == bucket_ms)
            .unwrap_or_else(|| panic!("no bucket_ms={bucket_ms} in the committed artifact"))
            .paths
            .iter()
            .find(|p| {
                p.path == path
                    && p.cardinality == cardinality
                    && p.selector.contains(selector_substr)
            })
            .unwrap_or_else(|| {
                panic!(
                    "no cell path={path} cardinality={cardinality} selector~={selector_substr:?} \
                     in the committed artifact"
                )
            })
    }

    /// The report's scale-invariant comparative claim: **idx loses to the
    /// SQL fallback on the wide scans (`Regex5xx`, `NegBroad`) at every
    /// committed cardinality** — issue #34 CODE review round-2 [valid]
    /// finding #1 (the prose previously asserted "idx > sql in every
    /// row", which the committed JSON itself refutes), refined by round-3
    /// [precision] finding #2 into two separate claims: this test covers
    /// the scale-invariant wide-scan loss (checked at all three committed
    /// cardinalities, both bucket sizes); the bounded positive-equality
    /// selectors' cardinality-dependent *crossover* is the separate
    /// [`idx_vs_sql_fallback_on_bounded_positive_selectors_crosses_over_by_cardinality`]
    /// test below.
    #[test]
    fn idx_loses_to_sql_fallback_on_wide_scans_at_every_committed_cardinality() {
        let report = load_committed_report();
        for &bucket_ms in &[3_600_000i64, 86_400_000i64] {
            for &card in &[1_000u64, 10_000, 50_000] {
                let sql_regex = find(&report, bucket_ms, "sql_fallback", card, "status=~");
                let idx_regex = find(&report, bucket_ms, "idx_prototype", card, "status=~");
                assert!(
                    idx_regex.wall_ms_p50 > sql_regex.wall_ms_p50,
                    "bucket_ms={bucket_ms} cardinality={card}: expected idx to lose to \
                     sql_fallback on Regex5xx (idx={} sql={})",
                    idx_regex.wall_ms_p50,
                    sql_regex.wall_ms_p50
                );

                let sql_neg = find(&report, bucket_ms, "sql_fallback", card, "job!=");
                let idx_neg = find(&report, bucket_ms, "idx_prototype", card, "job!=");
                assert!(
                    idx_neg.wall_ms_p50 > sql_neg.wall_ms_p50,
                    "bucket_ms={bucket_ms} cardinality={card}: expected idx to lose to \
                     sql_fallback on NegBroad (idx={} sql={})",
                    idx_neg.wall_ms_p50,
                    sql_neg.wall_ms_p50
                );
            }
        }
    }

    /// The idx-vs-sql-fallback win/loss split on the two **bounded
    /// positive-equality** selectors is **not** scale-invariant (issue #34
    /// CODE review round-3 [precision] finding #2 — round-2's version of
    /// this test asserted only `metric_50000` and so overclaimed a
    /// uniform "idx wins" verdict). It is a **crossover**: sql_fallback
    /// wins both `NarrowEq` and `BroadEq` at the smallest committed
    /// cardinality (1,000), idx wins both at the largest (50,000), and the
    /// crossover itself sits somewhere around 10,000 (`BroadEq` has
    /// already crossed by 10,000 in both bucket passes; `NarrowEq`'s
    /// crossover point falls close enough to 10,000 that this corpus's
    /// two bucket passes disagree on which side of it 10,000 lands —
    /// **deliberately not asserted** here to avoid a flaky assertion on
    /// bench-run noise; the two endpoints below are the stable,
    /// unambiguous claim).
    #[test]
    fn idx_vs_sql_fallback_on_bounded_positive_selectors_crosses_over_by_cardinality() {
        let report = load_committed_report();
        for &bucket_ms in &[3_600_000i64, 86_400_000i64] {
            // Low cardinality (1,000): sql_fallback wins everywhere,
            // including the bounded positive-equality selectors.
            for sel in ["pod=", "job=\"j0\""] {
                let sql = find(&report, bucket_ms, "sql_fallback", 1_000, sel);
                let idx = find(&report, bucket_ms, "idx_prototype", 1_000, sel);
                assert!(
                    idx.wall_ms_p50 > sql.wall_ms_p50,
                    "bucket_ms={bucket_ms} cardinality=1000 selector={sel:?}: expected \
                     sql_fallback to win at low cardinality (idx={} sql={})",
                    idx.wall_ms_p50,
                    sql.wall_ms_p50
                );
            }

            // High cardinality (50,000): idx has overtaken sql_fallback on
            // both bounded positive-equality selectors — the crossover
            // has completed.
            for sel in ["pod=", "job=\"j0\""] {
                let sql = find(&report, bucket_ms, "sql_fallback", 50_000, sel);
                let idx = find(&report, bucket_ms, "idx_prototype", 50_000, sel);
                assert!(
                    idx.wall_ms_p50 < sql.wall_ms_p50,
                    "bucket_ms={bucket_ms} cardinality=50000 selector={sel:?}: expected idx \
                     to have overtaken sql_fallback at high cardinality (idx={} sql={})",
                    idx.wall_ms_p50,
                    sql.wall_ms_p50
                );
            }

            // Mid cardinality (10,000): `BroadEq` has already crossed over
            // (stable in both bucket passes); `NarrowEq` has not (or has
            // only just, depending on bucket size) — asserted loosely
            // (idx must at least be competitive, not asserted as an
            // outright win) to avoid pinning a noise-prone boundary.
            let sql_broad = find(&report, bucket_ms, "sql_fallback", 10_000, "job=\"j0\"");
            let idx_broad = find(&report, bucket_ms, "idx_prototype", 10_000, "job=\"j0\"");
            assert!(
                idx_broad.wall_ms_p50 < sql_broad.wall_ms_p50,
                "bucket_ms={bucket_ms} cardinality=10000: expected idx to have already \
                 crossed over on BroadEq (idx={} sql={})",
                idx_broad.wall_ms_p50,
                sql_broad.wall_ms_p50
            );
        }
    }

    /// The report's structural claim: `read_rows` is identical (metric
    /// scan is already saturated) regardless of bucket size, for the SQL
    /// fallback path.
    #[test]
    fn read_rows_ratio_is_saturated_at_one_for_every_committed_cardinality() {
        let report = load_committed_report();
        for o in &report.over_inclusion {
            assert_eq!(
                o.ratio, 1.0,
                "cardinality={}: expected the structural read_rows ratio to be exactly 1.0 \
                 (metric_series' fingerprint-before-time primary key prunes zero granules \
                 regardless of bucket size) — got {}",
                o.cardinality, o.ratio
            );
        }
    }

    /// The report's semantic over-inclusion claim: the deduplicated
    /// candidate ratio is materially larger than 1 — the observable
    /// `read_rows` cannot show (previous finding), but `matched_candidates`
    /// can.
    #[test]
    fn candidate_ratio_shows_material_over_inclusion() {
        let report = load_committed_report();
        assert!(
            !report.over_inclusion.is_empty(),
            "expected at least one over_inclusion row in the committed artifact"
        );
        for o in &report.over_inclusion {
            assert!(
                o.candidate_ratio > 5.0,
                "cardinality={}: expected a material (>5x) semantic over-inclusion ratio, got {}",
                o.cardinality,
                o.candidate_ratio
            );
        }
    }
}
