//! Query parameters supplied by #13 (the HTTP query handler) and the
//! resolved table/budget context supplied by the server's schema/config
//! wiring. `QuerySpec` makes instant-vs-range evaluation a type-level
//! distinction (task-manager resolution #3, architect plan amendment §3):
//! an instant metric query structurally cannot pick up range bucketing or a
//! magic `step_ns` value, because there is no `step_ns` field to reach for
//! in the `Instant` variant.

/// Result ordering for stream reads. Loki's LogQL default is newest-first
/// (`Backward`); `Forward` reverses it. Range/instant metric evaluation is
/// unaffected — direction only orders stage 3's `log_samples` rows.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub enum Direction {
    Forward,
    #[default]
    Backward,
}

/// The evaluation shape for a query. `Instant` evaluates one window `[at -
/// range, at]` (the `range` comes from the query's own range-vector
/// duration, e.g. `[5m]`, for metric queries; stream queries have no
/// window narrower than the caller-supplied bound) and produces a single
/// aggregate per series, never an `intDiv` bucket expression. `Range`
/// produces the step-aligned bucketed shape (docs/schemas.md §3.2).
///
/// **M1 rate semantic (task-manager resolution #4):** `Range` bucketing is
/// *fixed, step-aligned, non-overlapping* — `intDiv(ts, step) * step` tumbling
/// windows — not Prometheus/Loki's sliding `[range]` window re-evaluated at
/// every step. A query whose step does not divide evenly into whole
/// buckets, or whose declared range differs from its step, still buckets by
/// `step` alone; the range-vector duration only bounds which raw samples
/// are considered eligible for rollup routing. This is a documented M1
/// simplification, not sliding-window parity — full parity is an M6
/// concern.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum QuerySpec {
    Instant {
        at_ns: i64,
    },
    Range {
        start_ns: i64,
        end_ns: i64,
        step_ns: u64,
    },
}

/// Parameters for one query evaluation, supplied by #13.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct QueryParams {
    pub spec: QuerySpec,
    pub limit: u32,
    pub direction: Direction,
}

/// Resolved table names, rollup resolution, and per-query budget — supplied
/// by the server (base vs `_dist` table-name resolution is cluster-aware and
/// lives in #13's config wiring, not here).
#[derive(Debug, Clone, Copy)]
pub struct PlanCtx<'a> {
    /// `CLICKHOUSE_DB` / `clickhouse.database` — carried through for
    /// downstream consumers (e.g. `EXPLAIN`/connection context); the SQL
    /// generated by this module deliberately does not prefix table names
    /// with it so pure-positive selectors stay byte-exact to
    /// docs/schemas.md §3.2's unqualified canonical examples. The
    /// connection's own default database resolves unqualified names.
    pub db: &'a str,
    pub streams_idx: &'a str,
    pub streams: &'a str,
    pub samples: &'a str,
    pub rollup_table: &'a str,
    pub rollup_res_ns: u64,
    pub scan_budget_bytes: u64,
    pub max_streams: usize,
}

/// A `[start_ns, end_ns]` time window for label/series discovery reads
/// (#13's `labels`/`label/{name}/values`/`series` endpoints supply this
/// from parsed `start`/`end` query params). Deliberately distinct from
/// [`QueryParams`]/[`QuerySpec`]: discovery reads never bucket or evaluate
/// a range aggregation, they only bound which `log_streams_idx` months
/// ([`super::plan::months_overlapping`]) to scan.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct TimeBounds {
    pub start_ns: i64,
    pub end_ns: i64,
}

/// Hard structural cap on the number of fingerprints stage 1 may resolve
/// before hydration/sample reads (task-manager resolution #1 on issue #11):
/// a documented constant, not a config field, same precedent as #8's
/// decompress cap and #9's spool dir/LRU cap. Promote to a
/// `PULSUS_LOGQL_MAX_STREAMS` config field only when a deployment needs it.
pub const DEFAULT_MAX_STREAMS: usize = 100_000;

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn direction_defaults_to_backward() {
        assert_eq!(Direction::default(), Direction::Backward);
    }

    #[test]
    fn instant_spec_carries_no_step() {
        // Structural assertion: `Instant` has no `step_ns` field to read at
        // all, so this is a compile-time guarantee, not just a runtime one.
        let spec = QuerySpec::Instant { at_ns: 100 };
        match spec {
            QuerySpec::Instant { at_ns } => assert_eq!(at_ns, 100),
            QuerySpec::Range { .. } => panic!("expected Instant"),
        }
    }

    #[test]
    fn time_bounds_carries_start_and_end_verbatim() {
        let b = TimeBounds {
            start_ns: 10,
            end_ns: 20,
        };
        assert_eq!(b.start_ns, 10);
        assert_eq!(b.end_ns, 20);
    }

    #[test]
    fn default_max_streams_is_the_documented_100k_constant() {
        assert_eq!(DEFAULT_MAX_STREAMS, 100_000);
    }
}
